apiVersion: apps/v1
kind: Deployment
metadata:
  name: provigos-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provigos-web
  template:
    metadata:
      labels:
        app: provigos-web
    spec:
      containers:
        - name: provigos-web
          image: provigos-web-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: provigos-env
---
apiVersion: v1
kind: Service
metadata:
  name: provigos-service
spec:
  type: NodePort
  selector:
    app: provigos-web
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
