name: Deploy React site to droplet

on:
  push:
    branches: main // replace branch_name with your branch
  pull_request:
    branches: main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm

      - name: Debug Port 3000 Usage
        run: |
          PORT_IN_USE=$(lsof -i tcp:3000 -t)
          if [ -z "$PORT_IN_USE" ]; then
              echo "No process is using port 3000"
          else
              echo "Process using port 3000: $PORT_IN_USE"
              echo "Killing process $PORT_IN_USE"
              kill -9 "$PORT_IN_USE"
              echo "Process killed"
          fi

      # Delete package-lock.json and node_modules
      - name: Clean Up
        run: |
          rm -rf package-lock.json node_modules

      - name: Install dependencies
        run: npm install --force
      - name: Build Project
        run: npm run build
      - name: Start server
        run: sudo npm run start &
